name: CI

on:
  push:
    branches:
      - main
      - 'feature-**'

jobs:
  test_phaser:
    name: Build and Test Phaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify directory structure
        run: |
          pwd
          ls -la
          echo "Current directory contents:"
          find . -maxdepth 2 -type d

      - name: Setup Rust toolchain
        run: |
          rustup update
          rustup component add clippy rustfmt
          rustup install nightly
          
      - name: Display toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        run: |
          if [ -d "phaser" ]; then
            cd phaser
          elif [ -d "../phaser" ]; then
            cd ../phaser
          else
            echo "Error: phaser directory not found"
            pwd
            ls -la
            exit 1
          fi
          cargo fmt -- --check

      - name: Run clippy
        run: |
          if [ -d "phaser" ]; then
            cd phaser
          elif [ -d "../phaser" ]; then
            cd ../phaser
          else
            echo "Error: phaser directory not found"
            pwd
            ls -la
            exit 1
          fi
          cargo clippy -- -D warnings

      - name: Check build
        run: |
          if [ -d "phaser" ]; then
            cd phaser
          elif [ -d "../phaser" ]; then
            cd ../phaser
          else
            echo "Error: phaser directory not found"
            pwd
            ls -la
            exit 1
          fi
          cargo check

      - name: Run tests
        run: |
          if [ -d "phaser" ]; then
            cd phaser
          elif [ -d "../phaser" ]; then
            cd ../phaser
          else
            echo "Error: phaser directory not found"
            pwd
            ls -la
            exit 1
          fi
          cargo test --all

      - name: Build release
        run: |
          if [ -d "phaser" ]; then
            cd phaser
          elif [ -d "../phaser" ]; then
            cd ../phaser
          else
            echo "Error: phaser directory not found"
            pwd
            ls -la
            exit 1
          fi
          cargo build --release
